steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone', 'https://github.com/turnonline/${REPO_NAME}.git']
  - name: gcr.io/cloud-builders/mvn
    entrypoint: 'mvn'
    args: ['package','-DskipTests']
    env:
      - 'ENDPOINTS_SERVICE_NAME=${_ENDPOINTS_SERVICE_DOMAIN}'
      - 'GCP_ID=${_FIREBASE_AUDIENCE_ALIAS}'
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args: ['-c','cat target/generated-sources/java-templates/biz/turnonline/ecosystem/payment/api/EndpointsApiProfile.java']
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args: ['-c','cat target/turnonline-payment-processor/WEB-INF/appengine-web.xml']
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args: ['-c', 'gcloud beta secrets versions access latest --secret=payment-processor-config > config.properties']
  - name: gcr.io/cloud-builders/gsutil
    args: ['mv','config.properties','target/turnonline-payment-processor/WEB-INF/classes/config.properties']
  - name: gcr.io/cloud-builders/gcloud
    args: ['app', 'deploy','target/turnonline-payment-processor']