steps:
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp','-n','gs://${PROJECT_ID}_cloudbuild/*/**-${COMMIT_SHA}.war','.']
  - name: gcr.io/cloud-builders/gsutil
    args: ['mv','*-${COMMIT_SHA}.war','build/artifact.war']
  - name: gcr.io/$PROJECT_ID/tar
    args: ['xzvf', 'build/artifact.war','-C','build' ]
  - name: gcr.io/cloud-builders/gcloud
    args: ['app', 'deploy','build']
