/*
 * Payment Processor
 * TurnOnline.biz Ecosystem Payment Processor
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package biz.turnonline.ecosystem.payment.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import javax.validation.constraints.NotNull;
import java.util.Objects;

/**
 * ErrorReason
 */
public class ErrorReason
{
    @JsonProperty( "domain" )
    private String domain = null;

    @JsonProperty( "message" )
    private String message = null;

    @JsonProperty( "reason" )
    private String reason = null;

    public ErrorReason domain( String domain )
    {
        this.domain = domain;
        return this;
    }

    /**
     * The overall scope of the error message.
     **/
    @JsonProperty( "domain" )
    @NotNull
    public String getDomain()
    {
        return domain;
    }

    public void setDomain( String domain )
    {
        this.domain = domain;
    }

    public ErrorReason message( String message )
    {
        this.message = message;
        return this;
    }

    /**
     * The detailed error message.
     **/
    @JsonProperty( "message" )
    @NotNull
    public String getMessage()
    {
        return message;
    }

    public void setMessage( String message )
    {
        this.message = message;
    }

    public ErrorReason reason( String reason )
    {
        this.reason = reason;
        return this;
    }

    /**
     * The error reason (error key).
     **/
    @JsonProperty( "reason" )
    @NotNull
    public String getReason()
    {
        return reason;
    }

    public void setReason( String reason )
    {
        this.reason = reason;
    }

    @Override
    public boolean equals( Object o )
    {
        if ( this == o )
        {
            return true;
        }
        if ( o == null || getClass() != o.getClass() )
        {
            return false;
        }
        ErrorReason errorReason = ( ErrorReason ) o;
        return Objects.equals( this.domain, errorReason.domain ) &&
                Objects.equals( this.message, errorReason.message ) &&
                Objects.equals( this.reason, errorReason.reason );
    }

    @Override
    public int hashCode()
    {
        return Objects.hash( domain, message, reason );
    }

    @Override
    public String toString()
    {
        return "class ErrorReason {\n" +
                "    domain: " + toIndentedString( domain ) + "\n" +
                "    message: " + toIndentedString( message ) + "\n" +
                "    reason: " + toIndentedString( reason ) + "\n" +
                "}";
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString( Object o )
    {
        if ( o == null )
        {
            return "null";
        }
        return o.toString().replace( "\n", "\n    " );
    }
}
